"""Schema 元信息常量。"""

LIBRARY_SCHEMA_VERSION_KEY = "schema_version"
LIBRARY_SCHEMA_VERSION_VALUE = "1"
LIBRARY_SCHEMA_NAME_KEY = "product_schema_name"
LIBRARY_SCHEMA_NAME_VALUE = "people_gallery_v1"

EMBEDDING_SCHEMA_VERSION_KEY = "schema_version"
EMBEDDING_SCHEMA_VERSION_VALUE = "1"
EMBEDDING_VECTOR_DIM_KEY = "vector_dim"
EMBEDDING_VECTOR_DTYPE_KEY = "vector_dtype"
EMBEDDING_VECTOR_DIM_VALUE = "512"
EMBEDDING_VECTOR_DTYPE_VALUE = "float32"
